name: Info

env:
  defaultLinuxRunner: ${{ env.linux && env.link || 'ubuntu-latest' }}

on:
  workflow_dispatch:

jobs:
  cpu:
    runs-on: ${ env.defaultLinuxRunner }

    steps:
    - name: lscpu
      run: lscpu

    - name: cpuinfo
      run: cat /proc/cpuinfo
      
    - name: meminfo
      run: cat /proc/meminfo
