name: Info

env:
  DEFAULT_LINUX_RUNNER: ${{ env.DEFAULT_LINUX_RUNNER && env.DEFAULT_LINUX_RUNNER || 'ubuntu-latest' }}

on:
  workflow_dispatch:

jobs:
  cpu:
    runs-on: ${ env.DEFAULT_LINUX_RUNNER }

    steps:
    - name: lscpu
      run: lscpu

    - name: cpuinfo
      run: cat /proc/cpuinfo
      
    - name: meminfo
      run: cat /proc/meminfo
